CREATE TABLE jspbook.BOARD(
NUM INTEGER(8) NOT NULL,
NAME VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(20) NOT NULL,
SUBJECT VARCHAR(50) NOT NULL,
CONTENT VARCHAR(500)  NOT NULL,
WRITE_DATE DATE  NOT NULL,
WRITE_TIME TIME  NOT NULL,
REF INTEGER(8)  NOT NULL,
STEP INTEGER(4)  NOT NULL,
LEV INTEGER(4)  NOT NULL,
READ_CNT INTEGER(8)  NOT NULL,
CHILD_CNT INTEGER(4)  NOT NULL,
PRIMARY KEY(NUM)
);